# Generated by Django 5.2.3 on 2025-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='account_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposite',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
