# Generated by Django 5.2.3 on 2025-06-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0008_createpassbook_account_type_createpassbook_address_and_more'),
        ('bankservice', '0002_deposite_account_type_deposite_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='user_reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankcustomer.openingbankaccount'),
            preserve_default=False,
        ),
    ]
