# Generated by Django 5.2.3 on 2025-06-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0008_createpassbook_account_type_createpassbook_address_and_more'),
        ('bankservice', '0003_deposite_user_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='bank_account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankcustomer.createpassbook', unique=True),
        ),
    ]
