# Generated by Django 5.2.3 on 2025-06-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankservice', '0004_alter_deposite_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='bank_account_number',
            field=models.BigIntegerField(),
        ),
    ]
