# Generated by Django 5.2.3 on 2025-06-27 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0008_createpassbook_account_type_createpassbook_address_and_more'),
        ('bankservice', '0005_alter_deposite_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='user_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankcustomer.createpassbook'),
        ),
    ]
