# Generated by Django 5.2.3 on 2025-06-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0009_createpassbook_total_balance'),
        ('bankservice', '0006_alter_deposite_user_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.BigIntegerField()),
                ('withdraw_date', models.DateTimeField(auto_now_add=True)),
                ('withdraw_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_type', models.CharField(max_length=20)),
                ('purpose', models.TextField(max_length=200)),
                ('reference_number', models.BigIntegerField(unique=True)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankcustomer.createpassbook')),
            ],
        ),
    ]
