# Generated by Django 5.2.3 on 2025-06-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0009_createpassbook_total_balance'),
        ('bankservice', '0008_withdraw_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='user_reference',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_type', models.CharField(max_length=20)),
                ('purpose', models.TextField(max_length=200)),
                ('reference_number', models.BigIntegerField(unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankcustomer.createpassbook')),
            ],
        ),
        migrations.DeleteModel(
            name='Deposite',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
