# Generated by Django 5.2.3 on 2025-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Asst.Manager', 'Asst.Manager'), ('Accountant', 'Accountant'), ('Cashier', 'Cashier'), ('Loan-Section', 'Loan-Section')], max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('pf_number', models.BigIntegerField(unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=20, unique=True)),
                ('ifsc_code', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
    ]
