# Generated by Django 5.2.3 on 2025-06-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_register', '0002_signupemployees_user_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupemployees',
            name='confirm_password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='signupemployees',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='signupemployees',
            name='user_reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer_register.employee_register'),
        ),
    ]
