# Generated by Django 4.2.23 on 2025-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=10)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(choices=[(1, 'Tamil nadu'), (2, 'Kerala'), (3, 'Andra pradesh'), (4, 'Telengana'), (5, 'Karnataka'), (6, 'Pondichery')], max_length=20)),
                ('distric', models.CharField(choices=[(1, 'Madurai'), (2, 'Siavgangai'), (3, 'Melur'), (4, 'Coimbatore'), (5, 'Chennai'), (6, 'Erode'), (7, 'Salem'), (8, 'Nilagiri'), (9, 'Ramanathapuram'), (10, 'Jaffana')], max_length=20)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('adhaar_number', models.BigIntegerField(unique=True)),
                ('nominee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_relation', models.CharField(choices=[(1, 'Mother'), (2, 'Father'), (3, 'Blood-brother'), (4, 'Blood_sister'), (5, 'relation'), (6, 'others')], max_length=20)),
                ('nominee_aadhar_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('open_for', models.CharField(choices=[(1, 'Saving Account'), (2, 'Current Account'), (3, 'Salary Account'), (4, 'NRI Account'), (5, 'NAE Account'), (6, 'Employee Account')], max_length=50)),
                ('aggre', models.BooleanField(default=False)),
            ],
        ),
    ]
