# Generated by Django 4.2.23 on 2025-06-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingbankaccount',
            name='open_for',
        ),
        migrations.AddField(
            model_name='openingbankaccount',
            name='account_type',
            field=models.CharField(choices=[(1, 'Saving Account'), (2, 'Current Account'), (3, 'Salary Account'), (4, 'NRI Account'), (5, 'NAE Account'), (6, 'Employee Account')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openingbankaccount',
            name='nominee_relation',
            field=models.CharField(choices=[(1, 'Mother'), (2, 'Father'), (3, 'Wife'), (4, 'Husbend'), (5, 'Blood-brother'), (6, 'Blood_sister'), (7, 'relation'), (8, 'others')], max_length=20),
        ),
        migrations.CreateModel(
            name='CreatePassBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bank_account_number', models.BigIntegerField(unique=True)),
                ('ifsc_code', models.CharField(default='MIB0010242', max_length=10)),
                ('account_oppening_date', models.DateField(auto_now_add=True)),
                ('user_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bankcustomer.openingbankaccount')),
            ],
        ),
    ]
