# Generated by Django 4.2.23 on 2025-06-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0002_remove_openingbankaccount_open_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingbankaccount',
            old_name='account_type',
            new_name='open_for',
        ),
    ]
