# Generated by Django 4.2.23 on 2025-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0004_rename_open_for_openingbankaccount_acount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbankaccount',
            name='distric',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('Sivaganga', 'Siavgangai'), ('Melur', 'Melur'), ('Coimbatore', 'Coimbatore'), ('Chennai', 'Chennai'), ('Erode', 'Erode'), ('Salem', 'Salem'), ('Nilagiri', 'Nilagiri'), ('Ramanathapuram', 'Ramanathapuram'), ('Jaffana', 'Jaffana')], max_length=20),
        ),
        migrations.AlterField(
            model_name='openingbankaccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='openingbankaccount',
            name='state',
            field=models.CharField(choices=[('Tamil nadu', 'Tamil nadu'), ('Kerala', 'Kerala'), ('Andra pradesh', 'Andra pradesh'), ('Telengana', 'Telengana'), ('Karnataka', 'Karnataka'), ('Pondichery', 'Pondichery')], max_length=20),
        ),
    ]
