# Generated by Django 4.2.23 on 2025-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0005_alter_openingbankaccount_distric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbankaccount',
            name='acount_type',
            field=models.CharField(choices=[('Saving Account', 'Saving Account'), ('Current Account', 'Current Account'), ('Salary Account', 'Salary Account'), ('NRI Account', 'NRI Account'), ('NRE Account', 'NRE Account'), ('Employee Account', 'Employee Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='openingbankaccount',
            name='aggre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='openingbankaccount',
            name='distric',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('Sivagangi', 'Siavgangai'), ('Melur', 'Melur'), ('Coimbatore', 'Coimbatore'), ('Chennai', 'Chennai'), ('Erode', 'Erode'), ('Salem', 'Salem'), ('Nilagiri', 'Nilagiri'), ('Ramanathapuram', 'Ramanathapuram'), ('Jaffana', 'Jaffana')], max_length=20),
        ),
        migrations.AlterField(
            model_name='openingbankaccount',
            name='nominee_relation',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Wife', 'Wife'), ('Husbend', 'Husbend'), ('Blood-brother', 'Blood-brother'), ('Blood-sister', 'Blood-sister'), ('Relation', 'Relation'), ('others', 'others')], max_length=20),
        ),
    ]
