# Generated by Django 4.2.23 on 2025-06-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0006_alter_openingbankaccount_acount_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingbankaccount',
            old_name='acount_type',
            new_name='account_type',
        ),
    ]
