# Generated by Django 5.2.3 on 2025-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0007_rename_acount_type_openingbankaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpassbook',
            name='account_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createpassbook',
            name='address',
            field=models.TextField(default='Madurai'),
        ),
        migrations.AddField(
            model_name='createpassbook',
            name='mobile_number',
            field=models.BigIntegerField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
