# Generated by Django 5.2.3 on 2025-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcustomer', '0008_createpassbook_account_type_createpassbook_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpassbook',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
